import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T;
export type InputMaybe<T> = T;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: { input: string; output: string; }
};

export type G_Company = {
  addressLine: Scalars['String']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  email: Scalars['String']['output'];
  firebaseUid: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  municipality: G_Municipality;
  name: Scalars['String']['output'];
  prefecture: G_Prefecture;
  updatedAt: Scalars['ISO8601DateTime']['output'];
  webUrl?: Maybe<Scalars['String']['output']>;
};

/** Autogenerated input type of CreateCompany */
export type G_CreateCompanyInput = {
  addressLine: Scalars['String']['input'];
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
  firebaseUid: Scalars['String']['input'];
  municipalityId: Scalars['ID']['input'];
  name: Scalars['String']['input'];
  prefectureId: Scalars['ID']['input'];
  webUrl?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of CreateCompany. */
export type G_CreateCompanyPayload = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  company?: Maybe<G_Company>;
  errors: Array<Scalars['String']['output']>;
};

/** Autogenerated input type of CreateEntry */
export type G_CreateEntryInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  internId: Scalars['ID']['input'];
  jobId: Scalars['ID']['input'];
};

/** Autogenerated return type of CreateEntry. */
export type G_CreateEntryPayload = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  entry?: Maybe<G_Entry>;
  errors: Array<Scalars['String']['output']>;
};

/** Autogenerated input type of CreateIntern */
export type G_CreateInternInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  email: Scalars['String']['input'];
  fieldOfStudyId: Scalars['ID']['input'];
  firebaseUid: Scalars['String']['input'];
  majorName: Scalars['String']['input'];
  name: Scalars['String']['input'];
  schoolName: Scalars['String']['input'];
  schoolYearId: Scalars['ID']['input'];
};

/** Autogenerated return type of CreateIntern. */
export type G_CreateInternPayload = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  intern?: Maybe<G_Intern>;
};

/** Autogenerated input type of CreateJob */
export type G_CreateJobInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  companyId: Scalars['ID']['input'];
  internConditions: Scalars['String']['input'];
  isPublished: Scalars['Boolean']['input'];
  title: Scalars['String']['input'];
};

/** Autogenerated return type of CreateJob. */
export type G_CreateJobPayload = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  job?: Maybe<G_Job>;
};

/** Autogenerated input type of CreateOrGetRoom */
export type G_CreateOrGetRoomInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  companyId: Scalars['ID']['input'];
  internId: Scalars['ID']['input'];
};

/** Autogenerated return type of CreateOrGetRoom. */
export type G_CreateOrGetRoomPayload = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  room: G_Room;
};

export type G_Entry = {
  createdAt: Scalars['ISO8601DateTime']['output'];
  currentStatus: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  intern: G_Intern;
  internId: Scalars['ID']['output'];
  job: G_Job;
  jobId: Scalars['ID']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_FieldOfStudy = {
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_Intern = {
  createdAt: Scalars['ISO8601DateTime']['output'];
  email: Scalars['String']['output'];
  fieldOfStudy: G_FieldOfStudy;
  firebaseUid: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  majorName: Scalars['String']['output'];
  name: Scalars['String']['output'];
  schoolName: Scalars['String']['output'];
  schoolYear: G_SchoolYear;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_Job = {
  company: G_Company;
  companyId: Scalars['ID']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  internConditions: Scalars['String']['output'];
  isPublished: Scalars['Boolean']['output'];
  title: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_Message = {
  company?: Maybe<G_Company>;
  content: Scalars['String']['output'];
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  intern?: Maybe<G_Intern>;
  readAt?: Maybe<Scalars['ISO8601DateTime']['output']>;
  room: G_Room;
  sender: G_SenderUnion;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_Municipality = {
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  prefecture: G_Prefecture;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_Mutation = {
  createCompany?: Maybe<G_CreateCompanyPayload>;
  createEntry?: Maybe<G_CreateEntryPayload>;
  createIntern?: Maybe<G_CreateInternPayload>;
  createJob?: Maybe<G_CreateJobPayload>;
  createOrGetRoom?: Maybe<G_CreateOrGetRoomPayload>;
  sendMessage?: Maybe<G_SendMessagePayload>;
  updateJob?: Maybe<G_UpdateJobPayload>;
};


export type G_MutationCreateCompanyArgs = {
  input: G_CreateCompanyInput;
};


export type G_MutationCreateEntryArgs = {
  input: G_CreateEntryInput;
};


export type G_MutationCreateInternArgs = {
  input: G_CreateInternInput;
};


export type G_MutationCreateJobArgs = {
  input: G_CreateJobInput;
};


export type G_MutationCreateOrGetRoomArgs = {
  input: G_CreateOrGetRoomInput;
};


export type G_MutationSendMessageArgs = {
  input: G_SendMessageInput;
};


export type G_MutationUpdateJobArgs = {
  input: G_UpdateJobInput;
};

export type G_Prefecture = {
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  municipalities: Array<G_Municipality>;
  name: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_Query = {
  company?: Maybe<G_Company>;
  entries: Array<G_Entry>;
  fieldOfStudies: Array<G_FieldOfStudy>;
  intern?: Maybe<G_Intern>;
  job?: Maybe<G_Job>;
  jobs: Array<G_Job>;
  messages: Array<G_Message>;
  municipalities: Array<G_Municipality>;
  prefectures: Array<G_Prefecture>;
  room?: Maybe<G_Room>;
  rooms: Array<G_Room>;
  schoolYears: Array<G_SchoolYear>;
};


export type G_QueryCompanyArgs = {
  firebaseUid?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
};


export type G_QueryEntriesArgs = {
  internId?: InputMaybe<Scalars['ID']['input']>;
  jobId?: InputMaybe<Scalars['ID']['input']>;
};


export type G_QueryInternArgs = {
  firebaseUid?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
};


export type G_QueryJobArgs = {
  id: Scalars['ID']['input'];
};


export type G_QueryJobsArgs = {
  companyId?: InputMaybe<Scalars['ID']['input']>;
  isPublished?: InputMaybe<Scalars['Boolean']['input']>;
};


export type G_QueryMessagesArgs = {
  roomId: Scalars['ID']['input'];
};


export type G_QueryMunicipalitiesArgs = {
  prefectureId?: InputMaybe<Scalars['ID']['input']>;
};


export type G_QueryRoomArgs = {
  id: Scalars['ID']['input'];
};


export type G_QueryRoomsArgs = {
  companyId?: InputMaybe<Scalars['ID']['input']>;
  internId?: InputMaybe<Scalars['ID']['input']>;
};

export type G_Room = {
  company: G_Company;
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  intern: G_Intern;
  messages: Array<G_Message>;
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

export type G_SchoolYear = {
  createdAt: Scalars['ISO8601DateTime']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  updatedAt: Scalars['ISO8601DateTime']['output'];
};

/** Autogenerated input type of SendMessage */
export type G_SendMessageInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  companyId?: InputMaybe<Scalars['ID']['input']>;
  content: Scalars['String']['input'];
  internId?: InputMaybe<Scalars['ID']['input']>;
  roomId: Scalars['ID']['input'];
};

/** Autogenerated return type of SendMessage. */
export type G_SendMessagePayload = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  message?: Maybe<G_Message>;
};

export type G_SenderUnion = G_Company | G_Intern;

/** Autogenerated input type of UpdateJob */
export type G_UpdateJobInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']['input']>;
  id: Scalars['ID']['input'];
  internConditions?: InputMaybe<Scalars['String']['input']>;
  isPublished?: InputMaybe<Scalars['Boolean']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
};

/** Autogenerated return type of UpdateJob. */
export type G_UpdateJobPayload = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']['output']>;
  errors: Array<Scalars['String']['output']>;
  job?: Maybe<G_Job>;
};

export type G_CreateCompanyMutationVariables = Exact<{
  firebaseUid: Scalars['String']['input'];
  name: Scalars['String']['input'];
  email: Scalars['String']['input'];
  prefectureId: Scalars['ID']['input'];
  municipalityId: Scalars['ID']['input'];
  addressLine: Scalars['String']['input'];
}>;


export type G_CreateCompanyMutation = { createCompany?: { errors: Array<string>, company?: { id: string, firebaseUid: string, name: string, email: string, addressLine: string, prefecture: { id: string, name: string }, municipality: { id: string, name: string } } } };

export type G_GetCompanyQueryVariables = Exact<{
  firebaseUid?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
}>;


export type G_GetCompanyQuery = { company?: { id: string, firebaseUid: string, name: string, email: string, addressLine: string, createdAt: string, updatedAt: string, prefecture: { id: string, name: string }, municipality: { id: string, name: string } } };

export type G_GetPrefecturesQueryVariables = Exact<{ [key: string]: never; }>;


export type G_GetPrefecturesQuery = { prefectures: Array<{ id: string, name: string }> };

export type G_GetMunicipalitiesQueryVariables = Exact<{
  prefectureId?: InputMaybe<Scalars['ID']['input']>;
}>;


export type G_GetMunicipalitiesQuery = { municipalities: Array<{ id: string, name: string, prefecture: { id: string, name: string } }> };

export type G_CreateEntryMutationVariables = Exact<{
  internId: Scalars['ID']['input'];
  jobId: Scalars['ID']['input'];
}>;


export type G_CreateEntryMutation = { createEntry?: { errors: Array<string>, entry?: { id: string, internId: string, jobId: string, currentStatus: string, createdAt: string, updatedAt: string } } };

export type G_HasAppliedToJobQueryVariables = Exact<{
  internId?: InputMaybe<Scalars['ID']['input']>;
  jobId?: InputMaybe<Scalars['ID']['input']>;
}>;


export type G_HasAppliedToJobQuery = { entries: Array<{ id: string, internId: string, jobId: string, currentStatus: string, createdAt: string, updatedAt: string, job: { id: string, title: string, internConditions: string, isPublished: boolean, company: { id: string, name: string } } }> };

export type G_GetInternQueryVariables = Exact<{
  firebaseUid?: InputMaybe<Scalars['String']['input']>;
  id?: InputMaybe<Scalars['ID']['input']>;
}>;


export type G_GetInternQuery = { intern?: { id: string, firebaseUid: string, name: string, email: string, schoolName: string, majorName: string, createdAt: string, updatedAt: string, fieldOfStudy: { id: string, name: string }, schoolYear: { id: string, name: string } } };

export type G_CreateInternMutationVariables = Exact<{
  firebaseUid: Scalars['String']['input'];
  name: Scalars['String']['input'];
  email: Scalars['String']['input'];
  schoolName: Scalars['String']['input'];
  majorName: Scalars['String']['input'];
  fieldOfStudyId: Scalars['ID']['input'];
  schoolYearId: Scalars['ID']['input'];
}>;


export type G_CreateInternMutation = { createIntern?: { errors: Array<string>, intern?: { id: string, firebaseUid: string, name: string, email: string, schoolName: string, majorName: string, fieldOfStudy: { id: string, name: string }, schoolYear: { id: string, name: string } } } };

export type G_GetSchoolYearsQueryVariables = Exact<{ [key: string]: never; }>;


export type G_GetSchoolYearsQuery = { schoolYears: Array<{ id: string, name: string }> };

export type G_GetFieldOfStudiesQueryVariables = Exact<{ [key: string]: never; }>;


export type G_GetFieldOfStudiesQuery = { fieldOfStudies: Array<{ id: string, name: string }> };

export type G_CreateJobMutationVariables = Exact<{
  companyId: Scalars['ID']['input'];
  title: Scalars['String']['input'];
  internConditions: Scalars['String']['input'];
  isPublished: Scalars['Boolean']['input'];
}>;


export type G_CreateJobMutation = { createJob?: { errors: Array<string>, job?: { id: string, companyId: string, title: string, internConditions: string, isPublished: boolean, createdAt: string, updatedAt: string } } };

export type G_UpdateJobMutationVariables = Exact<{
  id: Scalars['ID']['input'];
  title?: InputMaybe<Scalars['String']['input']>;
  internConditions?: InputMaybe<Scalars['String']['input']>;
  isPublished?: InputMaybe<Scalars['Boolean']['input']>;
}>;


export type G_UpdateJobMutation = { updateJob?: { errors: Array<string>, job?: { id: string, companyId: string, title: string, internConditions: string, isPublished: boolean, createdAt: string, updatedAt: string } } };

export type G_GetJobsQueryVariables = Exact<{
  companyId?: InputMaybe<Scalars['ID']['input']>;
  isPublished?: InputMaybe<Scalars['Boolean']['input']>;
}>;


export type G_GetJobsQuery = { jobs: Array<{ id: string, companyId: string, title: string, internConditions: string, isPublished: boolean, createdAt: string, updatedAt: string, company: { id: string, name: string, addressLine: string, prefecture: { id: string, name: string }, municipality: { id: string, name: string } } }> };

export type G_GetJobQueryVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type G_GetJobQuery = { job?: { id: string, companyId: string, title: string, internConditions: string, isPublished: boolean, createdAt: string, updatedAt: string, company: { id: string, name: string, addressLine: string, prefecture: { id: string, name: string }, municipality: { id: string, name: string } } } };

export type G_GetRoomsQueryVariables = Exact<{
  internId?: InputMaybe<Scalars['ID']['input']>;
  companyId?: InputMaybe<Scalars['ID']['input']>;
}>;


export type G_GetRoomsQuery = { rooms: Array<{ id: string, createdAt: string, updatedAt: string, intern: { id: string, name: string, email: string, schoolName: string, majorName: string }, company: { id: string, name: string, email: string } }> };

export type G_GetRoomQueryVariables = Exact<{
  id: Scalars['ID']['input'];
}>;


export type G_GetRoomQuery = { room?: { id: string, createdAt: string, updatedAt: string, intern: { id: string, name: string, email: string, schoolName: string, majorName: string }, company: { id: string, name: string, email: string }, messages: Array<{ id: string, content: string, createdAt: string, readAt?: string, sender:
        | { id: string, name: string }
        | { id: string, name: string }
       }> } };

export type G_GetMessagesQueryVariables = Exact<{
  roomId: Scalars['ID']['input'];
}>;


export type G_GetMessagesQuery = { messages: Array<{ id: string, content: string, createdAt: string, readAt?: string, sender:
      | { id: string, name: string }
      | { id: string, name: string }
     }> };

export type G_CreateOrGetRoomMutationVariables = Exact<{
  input: G_CreateOrGetRoomInput;
}>;


export type G_CreateOrGetRoomMutation = { createOrGetRoom?: { errors: Array<string>, room: { id: string, createdAt: string, updatedAt: string, intern: { id: string, name: string }, company: { id: string, name: string } } } };

export type G_SendMessageMutationVariables = Exact<{
  input: G_SendMessageInput;
}>;


export type G_SendMessageMutation = { sendMessage?: { errors: Array<string>, message?: { id: string, content: string, createdAt: string, sender:
        | { id: string, name: string }
        | { id: string, name: string }
       } } };

export type G_GetCurrentInternQueryVariables = Exact<{
  firebaseUid: Scalars['String']['input'];
}>;


export type G_GetCurrentInternQuery = { intern?: { id: string, name: string, email: string, firebaseUid: string, schoolName: string, majorName: string, createdAt: string, updatedAt: string, fieldOfStudy: { id: string, name: string }, schoolYear: { id: string, name: string } } };

export type G_GetCurrentCompanyQueryVariables = Exact<{
  firebaseUid: Scalars['String']['input'];
}>;


export type G_GetCurrentCompanyQuery = { company?: { id: string, name: string, email: string, firebaseUid: string, addressLine: string, createdAt: string, updatedAt: string, prefecture: { id: string, name: string }, municipality: { id: string, name: string } } };


export const CreateCompanyDocument = gql`
    mutation CreateCompany($firebaseUid: String!, $name: String!, $email: String!, $prefectureId: ID!, $municipalityId: ID!, $addressLine: String!) {
  createCompany(
    input: {firebaseUid: $firebaseUid, name: $name, email: $email, prefectureId: $prefectureId, municipalityId: $municipalityId, addressLine: $addressLine}
  ) {
    company {
      id
      firebaseUid
      name
      email
      prefecture {
        id
        name
      }
      municipality {
        id
        name
      }
      addressLine
    }
    errors
  }
}
    `;
export type G_CreateCompanyMutationFn = Apollo.MutationFunction<G_CreateCompanyMutation, G_CreateCompanyMutationVariables>;

/**
 * __useCreateCompanyMutation__
 *
 * To run a mutation, you first call `useCreateCompanyMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateCompanyMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createCompanyMutation, { data, loading, error }] = useCreateCompanyMutation({
 *   variables: {
 *      firebaseUid: // value for 'firebaseUid'
 *      name: // value for 'name'
 *      email: // value for 'email'
 *      prefectureId: // value for 'prefectureId'
 *      municipalityId: // value for 'municipalityId'
 *      addressLine: // value for 'addressLine'
 *   },
 * });
 */
export function useCreateCompanyMutation(baseOptions?: Apollo.MutationHookOptions<G_CreateCompanyMutation, G_CreateCompanyMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<G_CreateCompanyMutation, G_CreateCompanyMutationVariables>(CreateCompanyDocument, options);
      }
export type CreateCompanyMutationHookResult = ReturnType<typeof useCreateCompanyMutation>;
export type CreateCompanyMutationResult = Apollo.MutationResult<G_CreateCompanyMutation>;
export type CreateCompanyMutationOptions = Apollo.BaseMutationOptions<G_CreateCompanyMutation, G_CreateCompanyMutationVariables>;
export const GetCompanyDocument = gql`
    query GetCompany($firebaseUid: String, $id: ID) {
  company(firebaseUid: $firebaseUid, id: $id) {
    id
    firebaseUid
    name
    email
    prefecture {
      id
      name
    }
    municipality {
      id
      name
    }
    addressLine
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetCompanyQuery__
 *
 * To run a query within a React component, call `useGetCompanyQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetCompanyQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetCompanyQuery({
 *   variables: {
 *      firebaseUid: // value for 'firebaseUid'
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetCompanyQuery(baseOptions?: Apollo.QueryHookOptions<G_GetCompanyQuery, G_GetCompanyQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetCompanyQuery, G_GetCompanyQueryVariables>(GetCompanyDocument, options);
      }
export function useGetCompanyLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetCompanyQuery, G_GetCompanyQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetCompanyQuery, G_GetCompanyQueryVariables>(GetCompanyDocument, options);
        }
export function useGetCompanySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetCompanyQuery, G_GetCompanyQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetCompanyQuery, G_GetCompanyQueryVariables>(GetCompanyDocument, options);
        }
export type GetCompanyQueryHookResult = ReturnType<typeof useGetCompanyQuery>;
export type GetCompanyLazyQueryHookResult = ReturnType<typeof useGetCompanyLazyQuery>;
export type GetCompanySuspenseQueryHookResult = ReturnType<typeof useGetCompanySuspenseQuery>;
export type GetCompanyQueryResult = Apollo.QueryResult<G_GetCompanyQuery, G_GetCompanyQueryVariables>;
export const GetPrefecturesDocument = gql`
    query GetPrefectures {
  prefectures {
    id
    name
  }
}
    `;

/**
 * __useGetPrefecturesQuery__
 *
 * To run a query within a React component, call `useGetPrefecturesQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetPrefecturesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetPrefecturesQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetPrefecturesQuery(baseOptions?: Apollo.QueryHookOptions<G_GetPrefecturesQuery, G_GetPrefecturesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetPrefecturesQuery, G_GetPrefecturesQueryVariables>(GetPrefecturesDocument, options);
      }
export function useGetPrefecturesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetPrefecturesQuery, G_GetPrefecturesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetPrefecturesQuery, G_GetPrefecturesQueryVariables>(GetPrefecturesDocument, options);
        }
export function useGetPrefecturesSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetPrefecturesQuery, G_GetPrefecturesQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetPrefecturesQuery, G_GetPrefecturesQueryVariables>(GetPrefecturesDocument, options);
        }
export type GetPrefecturesQueryHookResult = ReturnType<typeof useGetPrefecturesQuery>;
export type GetPrefecturesLazyQueryHookResult = ReturnType<typeof useGetPrefecturesLazyQuery>;
export type GetPrefecturesSuspenseQueryHookResult = ReturnType<typeof useGetPrefecturesSuspenseQuery>;
export type GetPrefecturesQueryResult = Apollo.QueryResult<G_GetPrefecturesQuery, G_GetPrefecturesQueryVariables>;
export const GetMunicipalitiesDocument = gql`
    query GetMunicipalities($prefectureId: ID) {
  municipalities(prefectureId: $prefectureId) {
    id
    name
    prefecture {
      id
      name
    }
  }
}
    `;

/**
 * __useGetMunicipalitiesQuery__
 *
 * To run a query within a React component, call `useGetMunicipalitiesQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetMunicipalitiesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetMunicipalitiesQuery({
 *   variables: {
 *      prefectureId: // value for 'prefectureId'
 *   },
 * });
 */
export function useGetMunicipalitiesQuery(baseOptions?: Apollo.QueryHookOptions<G_GetMunicipalitiesQuery, G_GetMunicipalitiesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetMunicipalitiesQuery, G_GetMunicipalitiesQueryVariables>(GetMunicipalitiesDocument, options);
      }
export function useGetMunicipalitiesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetMunicipalitiesQuery, G_GetMunicipalitiesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetMunicipalitiesQuery, G_GetMunicipalitiesQueryVariables>(GetMunicipalitiesDocument, options);
        }
export function useGetMunicipalitiesSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetMunicipalitiesQuery, G_GetMunicipalitiesQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetMunicipalitiesQuery, G_GetMunicipalitiesQueryVariables>(GetMunicipalitiesDocument, options);
        }
export type GetMunicipalitiesQueryHookResult = ReturnType<typeof useGetMunicipalitiesQuery>;
export type GetMunicipalitiesLazyQueryHookResult = ReturnType<typeof useGetMunicipalitiesLazyQuery>;
export type GetMunicipalitiesSuspenseQueryHookResult = ReturnType<typeof useGetMunicipalitiesSuspenseQuery>;
export type GetMunicipalitiesQueryResult = Apollo.QueryResult<G_GetMunicipalitiesQuery, G_GetMunicipalitiesQueryVariables>;
export const CreateEntryDocument = gql`
    mutation CreateEntry($internId: ID!, $jobId: ID!) {
  createEntry(input: {internId: $internId, jobId: $jobId}) {
    entry {
      id
      internId
      jobId
      currentStatus
      createdAt
      updatedAt
    }
    errors
  }
}
    `;
export type G_CreateEntryMutationFn = Apollo.MutationFunction<G_CreateEntryMutation, G_CreateEntryMutationVariables>;

/**
 * __useCreateEntryMutation__
 *
 * To run a mutation, you first call `useCreateEntryMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateEntryMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createEntryMutation, { data, loading, error }] = useCreateEntryMutation({
 *   variables: {
 *      internId: // value for 'internId'
 *      jobId: // value for 'jobId'
 *   },
 * });
 */
export function useCreateEntryMutation(baseOptions?: Apollo.MutationHookOptions<G_CreateEntryMutation, G_CreateEntryMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<G_CreateEntryMutation, G_CreateEntryMutationVariables>(CreateEntryDocument, options);
      }
export type CreateEntryMutationHookResult = ReturnType<typeof useCreateEntryMutation>;
export type CreateEntryMutationResult = Apollo.MutationResult<G_CreateEntryMutation>;
export type CreateEntryMutationOptions = Apollo.BaseMutationOptions<G_CreateEntryMutation, G_CreateEntryMutationVariables>;
export const HasAppliedToJobDocument = gql`
    query HasAppliedToJob($internId: ID, $jobId: ID) {
  entries(internId: $internId, jobId: $jobId) {
    id
    internId
    jobId
    currentStatus
    createdAt
    updatedAt
    job {
      id
      title
      internConditions
      isPublished
      company {
        id
        name
      }
    }
  }
}
    `;

/**
 * __useHasAppliedToJobQuery__
 *
 * To run a query within a React component, call `useHasAppliedToJobQuery` and pass it any options that fit your needs.
 * When your component renders, `useHasAppliedToJobQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useHasAppliedToJobQuery({
 *   variables: {
 *      internId: // value for 'internId'
 *      jobId: // value for 'jobId'
 *   },
 * });
 */
export function useHasAppliedToJobQuery(baseOptions?: Apollo.QueryHookOptions<G_HasAppliedToJobQuery, G_HasAppliedToJobQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_HasAppliedToJobQuery, G_HasAppliedToJobQueryVariables>(HasAppliedToJobDocument, options);
      }
export function useHasAppliedToJobLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_HasAppliedToJobQuery, G_HasAppliedToJobQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_HasAppliedToJobQuery, G_HasAppliedToJobQueryVariables>(HasAppliedToJobDocument, options);
        }
export function useHasAppliedToJobSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_HasAppliedToJobQuery, G_HasAppliedToJobQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_HasAppliedToJobQuery, G_HasAppliedToJobQueryVariables>(HasAppliedToJobDocument, options);
        }
export type HasAppliedToJobQueryHookResult = ReturnType<typeof useHasAppliedToJobQuery>;
export type HasAppliedToJobLazyQueryHookResult = ReturnType<typeof useHasAppliedToJobLazyQuery>;
export type HasAppliedToJobSuspenseQueryHookResult = ReturnType<typeof useHasAppliedToJobSuspenseQuery>;
export type HasAppliedToJobQueryResult = Apollo.QueryResult<G_HasAppliedToJobQuery, G_HasAppliedToJobQueryVariables>;
export const GetInternDocument = gql`
    query GetIntern($firebaseUid: String, $id: ID) {
  intern(firebaseUid: $firebaseUid, id: $id) {
    id
    firebaseUid
    name
    email
    schoolName
    majorName
    fieldOfStudy {
      id
      name
    }
    schoolYear {
      id
      name
    }
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetInternQuery__
 *
 * To run a query within a React component, call `useGetInternQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetInternQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetInternQuery({
 *   variables: {
 *      firebaseUid: // value for 'firebaseUid'
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetInternQuery(baseOptions?: Apollo.QueryHookOptions<G_GetInternQuery, G_GetInternQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetInternQuery, G_GetInternQueryVariables>(GetInternDocument, options);
      }
export function useGetInternLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetInternQuery, G_GetInternQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetInternQuery, G_GetInternQueryVariables>(GetInternDocument, options);
        }
export function useGetInternSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetInternQuery, G_GetInternQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetInternQuery, G_GetInternQueryVariables>(GetInternDocument, options);
        }
export type GetInternQueryHookResult = ReturnType<typeof useGetInternQuery>;
export type GetInternLazyQueryHookResult = ReturnType<typeof useGetInternLazyQuery>;
export type GetInternSuspenseQueryHookResult = ReturnType<typeof useGetInternSuspenseQuery>;
export type GetInternQueryResult = Apollo.QueryResult<G_GetInternQuery, G_GetInternQueryVariables>;
export const CreateInternDocument = gql`
    mutation CreateIntern($firebaseUid: String!, $name: String!, $email: String!, $schoolName: String!, $majorName: String!, $fieldOfStudyId: ID!, $schoolYearId: ID!) {
  createIntern(
    input: {firebaseUid: $firebaseUid, name: $name, email: $email, schoolName: $schoolName, majorName: $majorName, fieldOfStudyId: $fieldOfStudyId, schoolYearId: $schoolYearId}
  ) {
    intern {
      id
      firebaseUid
      name
      email
      schoolName
      majorName
      fieldOfStudy {
        id
        name
      }
      schoolYear {
        id
        name
      }
    }
    errors
  }
}
    `;
export type G_CreateInternMutationFn = Apollo.MutationFunction<G_CreateInternMutation, G_CreateInternMutationVariables>;

/**
 * __useCreateInternMutation__
 *
 * To run a mutation, you first call `useCreateInternMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateInternMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createInternMutation, { data, loading, error }] = useCreateInternMutation({
 *   variables: {
 *      firebaseUid: // value for 'firebaseUid'
 *      name: // value for 'name'
 *      email: // value for 'email'
 *      schoolName: // value for 'schoolName'
 *      majorName: // value for 'majorName'
 *      fieldOfStudyId: // value for 'fieldOfStudyId'
 *      schoolYearId: // value for 'schoolYearId'
 *   },
 * });
 */
export function useCreateInternMutation(baseOptions?: Apollo.MutationHookOptions<G_CreateInternMutation, G_CreateInternMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<G_CreateInternMutation, G_CreateInternMutationVariables>(CreateInternDocument, options);
      }
export type CreateInternMutationHookResult = ReturnType<typeof useCreateInternMutation>;
export type CreateInternMutationResult = Apollo.MutationResult<G_CreateInternMutation>;
export type CreateInternMutationOptions = Apollo.BaseMutationOptions<G_CreateInternMutation, G_CreateInternMutationVariables>;
export const GetSchoolYearsDocument = gql`
    query GetSchoolYears {
  schoolYears {
    id
    name
  }
}
    `;

/**
 * __useGetSchoolYearsQuery__
 *
 * To run a query within a React component, call `useGetSchoolYearsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetSchoolYearsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetSchoolYearsQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetSchoolYearsQuery(baseOptions?: Apollo.QueryHookOptions<G_GetSchoolYearsQuery, G_GetSchoolYearsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetSchoolYearsQuery, G_GetSchoolYearsQueryVariables>(GetSchoolYearsDocument, options);
      }
export function useGetSchoolYearsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetSchoolYearsQuery, G_GetSchoolYearsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetSchoolYearsQuery, G_GetSchoolYearsQueryVariables>(GetSchoolYearsDocument, options);
        }
export function useGetSchoolYearsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetSchoolYearsQuery, G_GetSchoolYearsQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetSchoolYearsQuery, G_GetSchoolYearsQueryVariables>(GetSchoolYearsDocument, options);
        }
export type GetSchoolYearsQueryHookResult = ReturnType<typeof useGetSchoolYearsQuery>;
export type GetSchoolYearsLazyQueryHookResult = ReturnType<typeof useGetSchoolYearsLazyQuery>;
export type GetSchoolYearsSuspenseQueryHookResult = ReturnType<typeof useGetSchoolYearsSuspenseQuery>;
export type GetSchoolYearsQueryResult = Apollo.QueryResult<G_GetSchoolYearsQuery, G_GetSchoolYearsQueryVariables>;
export const GetFieldOfStudiesDocument = gql`
    query GetFieldOfStudies {
  fieldOfStudies {
    id
    name
  }
}
    `;

/**
 * __useGetFieldOfStudiesQuery__
 *
 * To run a query within a React component, call `useGetFieldOfStudiesQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetFieldOfStudiesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetFieldOfStudiesQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetFieldOfStudiesQuery(baseOptions?: Apollo.QueryHookOptions<G_GetFieldOfStudiesQuery, G_GetFieldOfStudiesQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetFieldOfStudiesQuery, G_GetFieldOfStudiesQueryVariables>(GetFieldOfStudiesDocument, options);
      }
export function useGetFieldOfStudiesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetFieldOfStudiesQuery, G_GetFieldOfStudiesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetFieldOfStudiesQuery, G_GetFieldOfStudiesQueryVariables>(GetFieldOfStudiesDocument, options);
        }
export function useGetFieldOfStudiesSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetFieldOfStudiesQuery, G_GetFieldOfStudiesQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetFieldOfStudiesQuery, G_GetFieldOfStudiesQueryVariables>(GetFieldOfStudiesDocument, options);
        }
export type GetFieldOfStudiesQueryHookResult = ReturnType<typeof useGetFieldOfStudiesQuery>;
export type GetFieldOfStudiesLazyQueryHookResult = ReturnType<typeof useGetFieldOfStudiesLazyQuery>;
export type GetFieldOfStudiesSuspenseQueryHookResult = ReturnType<typeof useGetFieldOfStudiesSuspenseQuery>;
export type GetFieldOfStudiesQueryResult = Apollo.QueryResult<G_GetFieldOfStudiesQuery, G_GetFieldOfStudiesQueryVariables>;
export const CreateJobDocument = gql`
    mutation CreateJob($companyId: ID!, $title: String!, $internConditions: String!, $isPublished: Boolean!) {
  createJob(
    input: {companyId: $companyId, title: $title, internConditions: $internConditions, isPublished: $isPublished}
  ) {
    job {
      id
      companyId
      title
      internConditions
      isPublished
      createdAt
      updatedAt
    }
    errors
  }
}
    `;
export type G_CreateJobMutationFn = Apollo.MutationFunction<G_CreateJobMutation, G_CreateJobMutationVariables>;

/**
 * __useCreateJobMutation__
 *
 * To run a mutation, you first call `useCreateJobMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateJobMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createJobMutation, { data, loading, error }] = useCreateJobMutation({
 *   variables: {
 *      companyId: // value for 'companyId'
 *      title: // value for 'title'
 *      internConditions: // value for 'internConditions'
 *      isPublished: // value for 'isPublished'
 *   },
 * });
 */
export function useCreateJobMutation(baseOptions?: Apollo.MutationHookOptions<G_CreateJobMutation, G_CreateJobMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<G_CreateJobMutation, G_CreateJobMutationVariables>(CreateJobDocument, options);
      }
export type CreateJobMutationHookResult = ReturnType<typeof useCreateJobMutation>;
export type CreateJobMutationResult = Apollo.MutationResult<G_CreateJobMutation>;
export type CreateJobMutationOptions = Apollo.BaseMutationOptions<G_CreateJobMutation, G_CreateJobMutationVariables>;
export const UpdateJobDocument = gql`
    mutation UpdateJob($id: ID!, $title: String, $internConditions: String, $isPublished: Boolean) {
  updateJob(
    input: {id: $id, title: $title, internConditions: $internConditions, isPublished: $isPublished}
  ) {
    job {
      id
      companyId
      title
      internConditions
      isPublished
      createdAt
      updatedAt
    }
    errors
  }
}
    `;
export type G_UpdateJobMutationFn = Apollo.MutationFunction<G_UpdateJobMutation, G_UpdateJobMutationVariables>;

/**
 * __useUpdateJobMutation__
 *
 * To run a mutation, you first call `useUpdateJobMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useUpdateJobMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [updateJobMutation, { data, loading, error }] = useUpdateJobMutation({
 *   variables: {
 *      id: // value for 'id'
 *      title: // value for 'title'
 *      internConditions: // value for 'internConditions'
 *      isPublished: // value for 'isPublished'
 *   },
 * });
 */
export function useUpdateJobMutation(baseOptions?: Apollo.MutationHookOptions<G_UpdateJobMutation, G_UpdateJobMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<G_UpdateJobMutation, G_UpdateJobMutationVariables>(UpdateJobDocument, options);
      }
export type UpdateJobMutationHookResult = ReturnType<typeof useUpdateJobMutation>;
export type UpdateJobMutationResult = Apollo.MutationResult<G_UpdateJobMutation>;
export type UpdateJobMutationOptions = Apollo.BaseMutationOptions<G_UpdateJobMutation, G_UpdateJobMutationVariables>;
export const GetJobsDocument = gql`
    query GetJobs($companyId: ID, $isPublished: Boolean) {
  jobs(companyId: $companyId, isPublished: $isPublished) {
    id
    companyId
    company {
      id
      name
      prefecture {
        id
        name
      }
      municipality {
        id
        name
      }
      addressLine
    }
    title
    internConditions
    isPublished
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetJobsQuery__
 *
 * To run a query within a React component, call `useGetJobsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetJobsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetJobsQuery({
 *   variables: {
 *      companyId: // value for 'companyId'
 *      isPublished: // value for 'isPublished'
 *   },
 * });
 */
export function useGetJobsQuery(baseOptions?: Apollo.QueryHookOptions<G_GetJobsQuery, G_GetJobsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetJobsQuery, G_GetJobsQueryVariables>(GetJobsDocument, options);
      }
export function useGetJobsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetJobsQuery, G_GetJobsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetJobsQuery, G_GetJobsQueryVariables>(GetJobsDocument, options);
        }
export function useGetJobsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetJobsQuery, G_GetJobsQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetJobsQuery, G_GetJobsQueryVariables>(GetJobsDocument, options);
        }
export type GetJobsQueryHookResult = ReturnType<typeof useGetJobsQuery>;
export type GetJobsLazyQueryHookResult = ReturnType<typeof useGetJobsLazyQuery>;
export type GetJobsSuspenseQueryHookResult = ReturnType<typeof useGetJobsSuspenseQuery>;
export type GetJobsQueryResult = Apollo.QueryResult<G_GetJobsQuery, G_GetJobsQueryVariables>;
export const GetJobDocument = gql`
    query GetJob($id: ID!) {
  job(id: $id) {
    id
    companyId
    company {
      id
      name
      prefecture {
        id
        name
      }
      municipality {
        id
        name
      }
      addressLine
    }
    title
    internConditions
    isPublished
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetJobQuery__
 *
 * To run a query within a React component, call `useGetJobQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetJobQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetJobQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetJobQuery(baseOptions: Apollo.QueryHookOptions<G_GetJobQuery, G_GetJobQueryVariables> & ({ variables: G_GetJobQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetJobQuery, G_GetJobQueryVariables>(GetJobDocument, options);
      }
export function useGetJobLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetJobQuery, G_GetJobQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetJobQuery, G_GetJobQueryVariables>(GetJobDocument, options);
        }
export function useGetJobSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetJobQuery, G_GetJobQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetJobQuery, G_GetJobQueryVariables>(GetJobDocument, options);
        }
export type GetJobQueryHookResult = ReturnType<typeof useGetJobQuery>;
export type GetJobLazyQueryHookResult = ReturnType<typeof useGetJobLazyQuery>;
export type GetJobSuspenseQueryHookResult = ReturnType<typeof useGetJobSuspenseQuery>;
export type GetJobQueryResult = Apollo.QueryResult<G_GetJobQuery, G_GetJobQueryVariables>;
export const GetRoomsDocument = gql`
    query GetRooms($internId: ID, $companyId: ID) {
  rooms(internId: $internId, companyId: $companyId) {
    id
    createdAt
    updatedAt
    intern {
      id
      name
      email
      schoolName
      majorName
    }
    company {
      id
      name
      email
    }
  }
}
    `;

/**
 * __useGetRoomsQuery__
 *
 * To run a query within a React component, call `useGetRoomsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetRoomsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetRoomsQuery({
 *   variables: {
 *      internId: // value for 'internId'
 *      companyId: // value for 'companyId'
 *   },
 * });
 */
export function useGetRoomsQuery(baseOptions?: Apollo.QueryHookOptions<G_GetRoomsQuery, G_GetRoomsQueryVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetRoomsQuery, G_GetRoomsQueryVariables>(GetRoomsDocument, options);
      }
export function useGetRoomsLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetRoomsQuery, G_GetRoomsQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetRoomsQuery, G_GetRoomsQueryVariables>(GetRoomsDocument, options);
        }
export function useGetRoomsSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetRoomsQuery, G_GetRoomsQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetRoomsQuery, G_GetRoomsQueryVariables>(GetRoomsDocument, options);
        }
export type GetRoomsQueryHookResult = ReturnType<typeof useGetRoomsQuery>;
export type GetRoomsLazyQueryHookResult = ReturnType<typeof useGetRoomsLazyQuery>;
export type GetRoomsSuspenseQueryHookResult = ReturnType<typeof useGetRoomsSuspenseQuery>;
export type GetRoomsQueryResult = Apollo.QueryResult<G_GetRoomsQuery, G_GetRoomsQueryVariables>;
export const GetRoomDocument = gql`
    query GetRoom($id: ID!) {
  room(id: $id) {
    id
    createdAt
    updatedAt
    intern {
      id
      name
      email
      schoolName
      majorName
    }
    company {
      id
      name
      email
    }
    messages {
      id
      content
      createdAt
      readAt
      sender {
        ... on Intern {
          id
          name
        }
        ... on Company {
          id
          name
        }
      }
    }
  }
}
    `;

/**
 * __useGetRoomQuery__
 *
 * To run a query within a React component, call `useGetRoomQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetRoomQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetRoomQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetRoomQuery(baseOptions: Apollo.QueryHookOptions<G_GetRoomQuery, G_GetRoomQueryVariables> & ({ variables: G_GetRoomQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetRoomQuery, G_GetRoomQueryVariables>(GetRoomDocument, options);
      }
export function useGetRoomLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetRoomQuery, G_GetRoomQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetRoomQuery, G_GetRoomQueryVariables>(GetRoomDocument, options);
        }
export function useGetRoomSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetRoomQuery, G_GetRoomQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetRoomQuery, G_GetRoomQueryVariables>(GetRoomDocument, options);
        }
export type GetRoomQueryHookResult = ReturnType<typeof useGetRoomQuery>;
export type GetRoomLazyQueryHookResult = ReturnType<typeof useGetRoomLazyQuery>;
export type GetRoomSuspenseQueryHookResult = ReturnType<typeof useGetRoomSuspenseQuery>;
export type GetRoomQueryResult = Apollo.QueryResult<G_GetRoomQuery, G_GetRoomQueryVariables>;
export const GetMessagesDocument = gql`
    query GetMessages($roomId: ID!) {
  messages(roomId: $roomId) {
    id
    content
    createdAt
    readAt
    sender {
      ... on Intern {
        id
        name
      }
      ... on Company {
        id
        name
      }
    }
  }
}
    `;

/**
 * __useGetMessagesQuery__
 *
 * To run a query within a React component, call `useGetMessagesQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetMessagesQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetMessagesQuery({
 *   variables: {
 *      roomId: // value for 'roomId'
 *   },
 * });
 */
export function useGetMessagesQuery(baseOptions: Apollo.QueryHookOptions<G_GetMessagesQuery, G_GetMessagesQueryVariables> & ({ variables: G_GetMessagesQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetMessagesQuery, G_GetMessagesQueryVariables>(GetMessagesDocument, options);
      }
export function useGetMessagesLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetMessagesQuery, G_GetMessagesQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetMessagesQuery, G_GetMessagesQueryVariables>(GetMessagesDocument, options);
        }
export function useGetMessagesSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetMessagesQuery, G_GetMessagesQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetMessagesQuery, G_GetMessagesQueryVariables>(GetMessagesDocument, options);
        }
export type GetMessagesQueryHookResult = ReturnType<typeof useGetMessagesQuery>;
export type GetMessagesLazyQueryHookResult = ReturnType<typeof useGetMessagesLazyQuery>;
export type GetMessagesSuspenseQueryHookResult = ReturnType<typeof useGetMessagesSuspenseQuery>;
export type GetMessagesQueryResult = Apollo.QueryResult<G_GetMessagesQuery, G_GetMessagesQueryVariables>;
export const CreateOrGetRoomDocument = gql`
    mutation CreateOrGetRoom($input: CreateOrGetRoomInput!) {
  createOrGetRoom(input: $input) {
    room {
      id
      createdAt
      updatedAt
      intern {
        id
        name
      }
      company {
        id
        name
      }
    }
    errors
  }
}
    `;
export type G_CreateOrGetRoomMutationFn = Apollo.MutationFunction<G_CreateOrGetRoomMutation, G_CreateOrGetRoomMutationVariables>;

/**
 * __useCreateOrGetRoomMutation__
 *
 * To run a mutation, you first call `useCreateOrGetRoomMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateOrGetRoomMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createOrGetRoomMutation, { data, loading, error }] = useCreateOrGetRoomMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreateOrGetRoomMutation(baseOptions?: Apollo.MutationHookOptions<G_CreateOrGetRoomMutation, G_CreateOrGetRoomMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<G_CreateOrGetRoomMutation, G_CreateOrGetRoomMutationVariables>(CreateOrGetRoomDocument, options);
      }
export type CreateOrGetRoomMutationHookResult = ReturnType<typeof useCreateOrGetRoomMutation>;
export type CreateOrGetRoomMutationResult = Apollo.MutationResult<G_CreateOrGetRoomMutation>;
export type CreateOrGetRoomMutationOptions = Apollo.BaseMutationOptions<G_CreateOrGetRoomMutation, G_CreateOrGetRoomMutationVariables>;
export const SendMessageDocument = gql`
    mutation SendMessage($input: SendMessageInput!) {
  sendMessage(input: $input) {
    message {
      id
      content
      createdAt
      sender {
        ... on Intern {
          id
          name
        }
        ... on Company {
          id
          name
        }
      }
    }
    errors
  }
}
    `;
export type G_SendMessageMutationFn = Apollo.MutationFunction<G_SendMessageMutation, G_SendMessageMutationVariables>;

/**
 * __useSendMessageMutation__
 *
 * To run a mutation, you first call `useSendMessageMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useSendMessageMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [sendMessageMutation, { data, loading, error }] = useSendMessageMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useSendMessageMutation(baseOptions?: Apollo.MutationHookOptions<G_SendMessageMutation, G_SendMessageMutationVariables>) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useMutation<G_SendMessageMutation, G_SendMessageMutationVariables>(SendMessageDocument, options);
      }
export type SendMessageMutationHookResult = ReturnType<typeof useSendMessageMutation>;
export type SendMessageMutationResult = Apollo.MutationResult<G_SendMessageMutation>;
export type SendMessageMutationOptions = Apollo.BaseMutationOptions<G_SendMessageMutation, G_SendMessageMutationVariables>;
export const GetCurrentInternDocument = gql`
    query GetCurrentIntern($firebaseUid: String!) {
  intern(firebaseUid: $firebaseUid) {
    id
    name
    email
    firebaseUid
    schoolName
    majorName
    fieldOfStudy {
      id
      name
    }
    schoolYear {
      id
      name
    }
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetCurrentInternQuery__
 *
 * To run a query within a React component, call `useGetCurrentInternQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetCurrentInternQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetCurrentInternQuery({
 *   variables: {
 *      firebaseUid: // value for 'firebaseUid'
 *   },
 * });
 */
export function useGetCurrentInternQuery(baseOptions: Apollo.QueryHookOptions<G_GetCurrentInternQuery, G_GetCurrentInternQueryVariables> & ({ variables: G_GetCurrentInternQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetCurrentInternQuery, G_GetCurrentInternQueryVariables>(GetCurrentInternDocument, options);
      }
export function useGetCurrentInternLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetCurrentInternQuery, G_GetCurrentInternQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetCurrentInternQuery, G_GetCurrentInternQueryVariables>(GetCurrentInternDocument, options);
        }
export function useGetCurrentInternSuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetCurrentInternQuery, G_GetCurrentInternQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetCurrentInternQuery, G_GetCurrentInternQueryVariables>(GetCurrentInternDocument, options);
        }
export type GetCurrentInternQueryHookResult = ReturnType<typeof useGetCurrentInternQuery>;
export type GetCurrentInternLazyQueryHookResult = ReturnType<typeof useGetCurrentInternLazyQuery>;
export type GetCurrentInternSuspenseQueryHookResult = ReturnType<typeof useGetCurrentInternSuspenseQuery>;
export type GetCurrentInternQueryResult = Apollo.QueryResult<G_GetCurrentInternQuery, G_GetCurrentInternQueryVariables>;
export const GetCurrentCompanyDocument = gql`
    query GetCurrentCompany($firebaseUid: String!) {
  company(firebaseUid: $firebaseUid) {
    id
    name
    email
    firebaseUid
    prefecture {
      id
      name
    }
    municipality {
      id
      name
    }
    addressLine
    createdAt
    updatedAt
  }
}
    `;

/**
 * __useGetCurrentCompanyQuery__
 *
 * To run a query within a React component, call `useGetCurrentCompanyQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetCurrentCompanyQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetCurrentCompanyQuery({
 *   variables: {
 *      firebaseUid: // value for 'firebaseUid'
 *   },
 * });
 */
export function useGetCurrentCompanyQuery(baseOptions: Apollo.QueryHookOptions<G_GetCurrentCompanyQuery, G_GetCurrentCompanyQueryVariables> & ({ variables: G_GetCurrentCompanyQueryVariables; skip?: boolean; } | { skip: boolean; }) ) {
        const options = {...defaultOptions, ...baseOptions}
        return Apollo.useQuery<G_GetCurrentCompanyQuery, G_GetCurrentCompanyQueryVariables>(GetCurrentCompanyDocument, options);
      }
export function useGetCurrentCompanyLazyQuery(baseOptions?: Apollo.LazyQueryHookOptions<G_GetCurrentCompanyQuery, G_GetCurrentCompanyQueryVariables>) {
          const options = {...defaultOptions, ...baseOptions}
          return Apollo.useLazyQuery<G_GetCurrentCompanyQuery, G_GetCurrentCompanyQueryVariables>(GetCurrentCompanyDocument, options);
        }
export function useGetCurrentCompanySuspenseQuery(baseOptions?: Apollo.SkipToken | Apollo.SuspenseQueryHookOptions<G_GetCurrentCompanyQuery, G_GetCurrentCompanyQueryVariables>) {
          const options = baseOptions === Apollo.skipToken ? baseOptions : {...defaultOptions, ...baseOptions}
          return Apollo.useSuspenseQuery<G_GetCurrentCompanyQuery, G_GetCurrentCompanyQueryVariables>(GetCurrentCompanyDocument, options);
        }
export type GetCurrentCompanyQueryHookResult = ReturnType<typeof useGetCurrentCompanyQuery>;
export type GetCurrentCompanyLazyQueryHookResult = ReturnType<typeof useGetCurrentCompanyLazyQuery>;
export type GetCurrentCompanySuspenseQueryHookResult = ReturnType<typeof useGetCurrentCompanySuspenseQuery>;
export type GetCurrentCompanyQueryResult = Apollo.QueryResult<G_GetCurrentCompanyQuery, G_GetCurrentCompanyQueryVariables>;